import {StyleSheet} from 'react-native'

const styles = StyleSheet.create({
    container: {
      backgroundColor: '#1C1C1C',
      flex: 1,
      alignItems: "center",
      paddingTop: 70,
      },
      campos:{
        marginTop: 40,
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
      },
      footer:{
        flex:1,
        position:'absolute',
        bottom:0,
        flexDirection: 'row',
        paddingBottom:20,      
      },
      button:{
          width:320,
          height:50,
          backgroundColor:'#19cdce',
          alignItems:"center",
          padding:10,
          borderRadius:2,
          marginTop: 60,
          justifyContent:'center',
      }, 
      cadastro:{
        textAlign:'center',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'flex-start',
        color:'#19cdce',
        fontSize:30,
        marginTop:60,
        borderColor:'#1c1c1c',        
      },
      nome:{
        height: 50, 
        width: 320,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderWidth: 1,
        borderRadius:1,
        marginTop: 20,
        borderBottomColor: '#19cdce',
        color:'white',
        borderColor:'#1c1c1c',
        fontSize:16,
      },
      cpf:{
        height: 50, 
        width: 320,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderWidth: 1,
        borderRadius:1,
        marginTop: 20,
        borderBottomColor: '#19cdce',
        color:'white',
        borderColor:'#1c1c1c',
        fontSize:16,
      },
      email:{
        height: 50, 
        width: 320,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderWidth: 1,
        borderRadius:1,
        marginTop: 20,
        borderBottomColor: '#19cdce',
        color:'white',
        borderColor:'#1c1c1c',
        fontSize:16,
      },
});
  export default styles;