import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#1C1C1C',
        flex: 1,
        alignItems: "center",
        paddingTop: 70,
    },
    numero:{
        height: 50, 
        width: 320,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderRadius:1,
        borderBottomColor: '#19cdce',
        borderBottomWidth:1,
        color:'white',
        fontSize:16,
        marginBottom:20,
    },
    nome:{
        height: 50, 
        width: 320,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderRadius:1,
        borderBottomColor: '#19cdce',
        borderBottomWidth:1,
        color:'white',
        fontSize:16,
        marginBottom:20,
    },
    validade:{
        height: 50, 
        width: 150,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderBottomColor: "#19cdce",
        borderWidth: 1,
        borderRadius:2, 
        alignItems:'flex-start',
        justifyContent:'flex-start',
        borderColor:'#1c1c1c',
        color:'#fff'
    },
    cod:{
        height: 50, 
        width: 150,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderWidth: 1,
        borderRadius:2,
        justifyContent:'space-between',
        marginLeft:20,
        color:'white',
        borderBottomColor: "#19cdce",
        borderColor:'#1c1c1c',
        marginBottom: 20,        
    },
    pagamento: { 
        flexDirection: "column",
        alignItems: "center",
        paddingTop: 75,
    },
    datacod:{    
        flexDirection: 'row',
    },
    footer:{
        position:'absolute',
        bottom:0,
        flexDirection: 'row',
        paddingBottom:20,
      },
      button1: {
        width: 150,
        height: 45,
        backgroundColor: '#19cdce',
        alignItems: 'center',
        padding: 10,
        borderRadius: 2,
      },
      button2: {
        width: 150,
        height: 45,
        backgroundColor: '#19cdce',
        alignItems: 'center',
        padding: 10,
        borderRadius: 2,
        marginLeft:20,
      },
});
export default styles;