import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#1C1C1C',
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    numero:{
            height: 45, 
            width: 300,
            paddingLeft: 10,
            backgroundColor: '#31343d',
            borderBottomColor: "#19cdce",
            borderWidth: 1,
            borderRadius:2,
            marginTop: 20,
            borderColor:'#1c1c1c',
    },
    nome:{
        height: 45, 
        width: 300,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderBottomColor: "#19cdce",
        borderWidth: 1,
        borderRadius:2,
        marginTop: 10,
        borderColor:'#1c1c1c',
    },
    validade:{
        height: 45, 
        width: 120,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderBottomColor: "#19cdce",
        borderWidth: 1,
        borderRadius:2, 
        alignItems:'flex-start',
        justifyContent:'flex-start',
        borderColor:'#1c1c1c',
    },
    cod:{
        height: 45, 
        width: 155,
        paddingLeft: 10,
        backgroundColor: '#31343d',
        borderWidth: 1,
        borderRadius:2,
        alignItems:'flex-start',
        justifyContent:'space-between',
        marginStart:25,
        color:'white',
        borderBottomColor: "#19cdce",
        borderColor:'#1c1c1c',
    },
    pagamento: {        
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        marginBottom: 30,
    },
    card: {        
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        marginBottom: 30,
        marginTop:20,
        borderColor:'#1c1c1c',
    },
    button: {
        width: 140,
        height: 45,
        backgroundColor: '#19cdce',
        alignItems: 'center',
        padding: 10,
        borderRadius: 2,
        marginTop: 100,
        justifyContent:'space-between',
        marginStart:15
    },
    scrollView: {
        backgroundColor: '#1C1C1C',
    },
    cadastro: {
        textAlign: 'center',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#19cdce',
        fontSize: 30,
        marginTop: 50,
        marginBottom: 17,
    },
    intro: {
        textAlign: 'center',
        alignItems: 'center',
        justifyContent: 'flex-start',
        color: 'white',
        fontSize: 15,
        marginTop: 2,
        flexDirection: 'row',
        marginBottom:39,
    },
});
export default styles;